spring.application.name=somCooked
spring.datasource.password=N.n.yybr123
spring.datasource.url=jdbc:mysql://localhost:3306/cooked_db
spring.datasource.username=root
spring.datasource.name=cooked_db
spring.jpa.hibernate.ddl-auto=update
